EXPLORATION_MODE = "exploration"
NAVIGATION_MODE = "navigation"
FAST_MODE = "fast"
POI_MODE = "poi"
TACTILE_MODE = "tactile"
AUTO_MODE = "auto"
VALID_MODES = {EXPLORATION_MODE, NAVIGATION_MODE, FAST_MODE, POI_MODE, TACTILE_MODE, AUTO_MODE}

ACTION_FORWARD = "forward"
ACTION_SEARCH = "search"
ACTION_SLIGHT_LEFT = "slight_left"
ACTION_SLIGHT_RIGHT = "slight_right"
ACTION_STOP = "stop"
